name: ZAP DAST Scan

on:
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

jobs:
  zap-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker Image
      run: |
        docker pull ${{ vars.DOCKERHUB_USERNAME }}/python-app:dev-${{ github.sha }}
        docker tag ${{ vars.DOCKERHUB_USERNAME }}/python-app:dev-${{ github.sha }} my-app:latest

    - name: Run ZAP Baseline Scan (JSON only, allow warning exit codes)
      run: |
        docker run -d -p 8080:8080 my-app:latest
        sleep 10
        mkdir -p zap-output
        docker run -t --network host --user 0 -v $(pwd)/zap-output:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t http://localhost:8080 -J zap_report.json --autooff || true

    - name: Upload ZAP JSON Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-json-report
        path: zap-output/zap_report.json
