name: Deploy Existing Docker Image to Cloud Run

on:
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Lance seulement si le build docker a réussi
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: Configure Docker to use Google Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker Image from DockerHub
      run: |
        docker pull ${{ vars.DOCKERHUB_USERNAME }}/python-app:dev-${{ github.sha }}

    - name: Tag Docker Image for Artifact Registry
      run: |
        docker tag ${{ vars.DOCKERHUB_USERNAME }}/python-app:dev-${{ github.sha }} europe-west1-docker.pkg.dev/oval-replica-458206-s7/isen-python-app/isen-python-app:latest

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push europe-west1-docker.pkg.dev/oval-replica-458206-s7/isen-python-app/isen-python-app:latest

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: isen-python-app
        image: europe-west1-docker.pkg.dev/oval-replica-458206-s7/isen-python-app/isen-python-app:latest
        region: europe-west1
